# Site settings
title: rpaggi
email: ronaldo.paggi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal rpaggi's page
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rpaggi.com.br" # the base hostname & protocol for your site
twitter_username: rpaggi
github_username:  rpaggi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

post-thumb-default: /assets/img/default.png

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'app']

paginate: 5
